# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CDSI.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nCDSI.proto\x12\x0forg.signal.cdsi\"\xa8\x01\n\rClientRequest\x12\x15\n\raci_uak_pairs\x18\x01 \x01(\x0c\x12\x12\n\nprev_e164s\x18\x02 \x01(\x0c\x12\x11\n\tnew_e164s\x18\x03 \x01(\x0c\x12\x15\n\rdiscard_e164s\x18\x04 \x01(\x0c\x12\r\n\x05token\x18\x06 \x01(\x0c\x12\x11\n\ttoken_ack\x18\x07 \x01(\x08\x12 \n\x18return_acis_without_uaks\x18\x08 \x01(\x08\"s\n\x0e\x43lientResponse\x12\x1c\n\x14\x65\x31\x36\x34_pni_aci_triples\x18\x01 \x01(\x0c\x12\x18\n\x10retry_after_secs\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x03 \x01(\x0c\x12\x1a\n\x12\x64\x65\x62ug_permits_used\x18\x04 \x01(\x05\"^\n\x0b\x45nclaveLoad\x12\x11\n\tclear_all\x18\x01 \x01(\x08\x12\x1f\n\x17\x65\x31\x36\x34_aci_pni_uak_tuples\x18\x02 \x01(\x0c\x12\x1b\n\x13shared_token_secret\x18\x03 \x01(\x0c\"W\n\x14\x43lientHandshakeStart\x12\x18\n\x10test_only_pubkey\x18\x01 \x01(\x0c\x12\x10\n\x08\x65vidence\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65ndorsement\x18\x03 \x01(\x0c\x42\x19\n\x15org.signal.cdsi.protoP\x01\x62\x06proto3')



_CLIENTREQUEST = DESCRIPTOR.message_types_by_name['ClientRequest']
_CLIENTRESPONSE = DESCRIPTOR.message_types_by_name['ClientResponse']
_ENCLAVELOAD = DESCRIPTOR.message_types_by_name['EnclaveLoad']
_CLIENTHANDSHAKESTART = DESCRIPTOR.message_types_by_name['ClientHandshakeStart']
ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUEST,
  '__module__' : 'CDSI_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.cdsi.ClientRequest)
  })
_sym_db.RegisterMessage(ClientRequest)

ClientResponse = _reflection.GeneratedProtocolMessageType('ClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSE,
  '__module__' : 'CDSI_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.cdsi.ClientResponse)
  })
_sym_db.RegisterMessage(ClientResponse)

EnclaveLoad = _reflection.GeneratedProtocolMessageType('EnclaveLoad', (_message.Message,), {
  'DESCRIPTOR' : _ENCLAVELOAD,
  '__module__' : 'CDSI_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.cdsi.EnclaveLoad)
  })
_sym_db.RegisterMessage(EnclaveLoad)

ClientHandshakeStart = _reflection.GeneratedProtocolMessageType('ClientHandshakeStart', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTHANDSHAKESTART,
  '__module__' : 'CDSI_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.cdsi.ClientHandshakeStart)
  })
_sym_db.RegisterMessage(ClientHandshakeStart)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025org.signal.cdsi.protoP\001'
  _CLIENTREQUEST._serialized_start=32
  _CLIENTREQUEST._serialized_end=200
  _CLIENTRESPONSE._serialized_start=202
  _CLIENTRESPONSE._serialized_end=317
  _ENCLAVELOAD._serialized_start=319
  _ENCLAVELOAD._serialized_end=413
  _CLIENTHANDSHAKESTART._serialized_start=415
  _CLIENTHANDSHAKESTART._serialized_end=502
# @@protoc_insertion_point(module_scope)
