%YAML 1.2
---
# Interface facing the victim
ap:
  iface: TODO
# Access Point SSID
  ssid: TODO
# Access Point PW
  pw: good-password
  # Name of your interface which connects to the internet, e.g., "eth0" for Ethernet or "wlan0" for Wi-Fi.
  internet_iface: TODO
# The password for the kea client, choose whatever you want
kea:
  api_pw: TODO
# List of hosts (python regex) whose traffic the proxy should pass through.
mitmproxy:
  ignore_hosts_list: [ TODO, TODO, ... ]
